# Generated by Django 4.1 on 2022-09-16 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post_like_follower'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Tweet',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='post',
            new_name='tweet',
        ),
    ]
