# Generated by Django 4.1 on 2022-09-29 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_rename_post_tweet_rename_post_like_tweet'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follower',
            unique_together={('user', 'follower')},
        ),
    ]
