# Generated by Django 4.1 on 2022-09-30 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_follower_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('liker', 'tweet')},
        ),
    ]
