# Generated by Django 4.1 on 2022-09-01 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('startBid', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('category', models.CharField(max_length=64, null=True)),
                ('createDate', models.DateTimeField()),
                ('description', models.CharField(max_length=1024)),
            ],
        ),
    ]
