# Generated by Django 4.1 on 2022-09-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='createDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
