# Generated by Django 4.1 on 2022-09-02 08:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_watchlist_comments_bids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='startBid',
        ),
        migrations.AlterField(
            model_name='listings',
            name='category',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listings',
            name='image',
            field=models.ImageField(blank=True, default=23, upload_to=''),
            preserve_default=False,
        ),
    ]
