# Generated by Django 4.1 on 2022-09-06 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_listings_seller_listings_startbid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='category',
            field=models.CharField(blank=True, choices=[('EL', 'Electronics'), ('ColArt', 'Collectibles & Art'), ('HG', 'Home & Garden'), ('CSA', 'Clothing, Shoes & Accessories'), ('TH', 'Toys & Hobbies'), ('SG', 'Sporting Goods'), ('BMM', 'Books, Movies & Music'), ('HB', 'Health & Beauty'), ('BI', 'Business & Industrial'), ('BE', 'Baby Essentials'), ('PS', 'Pet Supplies')], max_length=64),
        ),
    ]
