# Generated by Django 4.1 on 2022-09-06 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_listings_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bids',
            old_name='listing_id',
            new_name='listing',
        ),
        migrations.RenameField(
            model_name='bids',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='listings',
            old_name='image',
            new_name='imageImg',
        ),
    ]
