# Generated by Django 4.1 on 2022-09-06 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_alter_listings_imageimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='startBid',
        ),
    ]
