# Generated by Django 4.1 on 2022-09-07 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_remove_listings_startbid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='closed',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
