# Generated by Django 4.1 on 2022-09-10 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_listings_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='category',
            field=models.CharField(blank=True, choices=[('Electronics', 'Electronics'), ('Collectibles & Art', 'Collectibles & Art'), ('Home & Garden', 'Home & Garden'), ('Clothing, Shoes & Accessories', 'Clothing, Shoes & Accessories'), ('Toys & Hobbies', 'Toys & Hobbies'), ('Sporting Goods', 'Sporting Goods'), ('Books, Movies & Music', 'Books, Movies & Music'), ('Health & Beauty', 'Health & Beauty'), ('Business & Industrial', 'Business & Industrial'), ('Baby Essentials', 'Baby Essentials'), ('Pet Supplies', 'Pet Supplies')], max_length=64),
        ),
    ]
